import bg from './bg.png'
import img from './img.png'
import blog1 from './blog1.jpg'
import blog2 from './blog2.jpg'
import donate1 from './donate1.jpg'
import donate2 from './donate2.jpg'
import concept from './concept.jpg'
import fertilizer1 from './fertilizer1.jpg'
import fertilizer2 from './fertilizer2.jpg'
import leftover1 from './leftover1.jpg'
import leftover2 from './leftover2.jpg'
import lifecycle from './lifecycle.jpg'
import trash from './trash.jpg'
import objects from './objects.jpg'
import rotten from './rotten.jpg'

export {bg, img, blog1, blog2, donate1, donate2, concept, leftover1, leftover2,fertilizer1,fertilizer2, lifecycle, trash, objects, rotten}